### ISSUE TITLE
Error compiling validator on Cygwin

### ISSUE THREAD

**Issue by toaarnio** [KhronosGroupArchives/webcl-validator#64]
I'm getting the following error when compiling the validator on Cygwin:

 `error: ‘EXIT_FAILURE’ was not declared in this scope`

And indeed, running `grep -r EXIT_FAILURE *` under webcl-validator reveals that `EXIT_FAILURE` is not defined anywhere.

**Comment by elhigu** [comment]
Actually I've been thinking to drop cygwin and mingw support from our side for now, since we already have support for Visual Studio. However this particular fix is so minor, that I think we can fix it. 

Since we don't have any developers currently using cygwin or mingw, in some cases it could be bigger effort for us to fix bugs of those targets. Would be great if in these cases people using those compilers could provide pull request, which we can then verify on our environments.

**Comment by toaarnio** [comment]
...and the same thing with `EXIT_SUCCESS`.

With those two added with `#define` in clv.h, the validator is successfully compiled.

However, when compiling `kernel-runner/main.cpp` I'm getting the same error message on `atoi()` and `atof()`.

**Comment by toaarnio** [comment]
OK, submitted pull request #65.
